### ISSUE TITLE
Screensaver not triggering on Ubuntu

### ISSUE THREAD

**Issue by vincerubinetti** [muffinista/before-dawn#30]
The app itself (the interface to select the screensaver and set options) installs and runs fine. But setting the trigger to 1 minute and leaving the mouse and keyboard alone doesn't seem to start the selected screensaver.

Is there anything I can do to debug what's going on? I'm not too familiar with electron; is there a way to open the chromium dev console (if that's even part of electron)?

I'm running Ubuntu 18, for what it's worth.

**Comment by muffinista** [comment]
I think I know what the problem is and I hope to have a fix out in the next day or two.

**Comment by muffinista** [comment]
OK, I think [this release](https://github.com/muffinista/before-dawn/releases/tag/v0.11.2) should fix the issue. Thanks for pointing it out!

**Comment by vincerubinetti** [comment]
Sorry for the late response.

Just tried the new version and unfortunately it doesn't seem to be working.

I downloaded the newest .deb package, installed it, set the screensaver to the sparks one, set the activate timeout to 1 minute, and waited 2 minutes (for good measure). It didn't trigger. For what it's worth, it also popped up with a message saying there was a new version available.

Ubuntu 18.04.3 LTS
GNOME 3.28.2

**Comment by muffinista** [comment]
OK, thanks for the update. It's working for me in a VM, but I don't have a physical box to test on right now. Would you mind killing the app, running `before-dawn` from a terminal, and then waiting a minute to see if it runs? Hopefully the app will output some useful logging information.

**Comment by vincerubinetti** [comment]
No problem, happy to help debug this as I know it's really difficult when you don't have access to a physical machine to test on. Here's the console output:

```
09:33:43.350 › Hello from version: 0.11.3 running in production
09:33:43.353 › use base path /home/vincerubinetti/.config/Before Dawn
09:33:43.377 › Loading prefs
09:33:43.378 › baseDir: /home/vincerubinetti/.config/Before Dawn
09:33:43.378 › systemSource: /opt/Before Dawn/resources/app.asar/output/system-savers
09:33:43.379 › updateStateManager idleTime: 1 blankTime: 6
09:33:43.379 › closeRunningScreensavers
09:33:43.379 › setupIfNeeded
09:33:43.380 › handleLocalPackage before-dawn-screensavers-v0.9.36.zip
09:33:43.380 › don't load savers from /opt/Before Dawn/resources/app.asar/data/before-dawn-screensavers-v0.9.36.zip
09:33:43.380 › checking if /home/vincerubinetti/.config/Before Dawn/savers/sparks/saver.json is valid
09:33:43.392 › looks like we are good to go
09:33:43.392 › openPrefsWindowIfNeeded
09:33:43.396 › Run initial release check
09:33:43.396 › checkForNewRelease
09:33:43.396 › check https://before-dawn.now.sh/update/win32/0.11.3 for new release
09:33:43.406 › Setup release check
09:33:43.407 › run initial package check
09:33:43.407 › checkForPackageUpdates
09:33:43.407 › register launch shortcut: Control+Command+S
09:33:43.408 › registered? true
09:33:43.408 › { downloaded: false }
09:33:43.409 › Setup recurring package check
09:33:43.795 › no update available, hide it
---
09:34:43.485 › runScreenSaverIfPowered
09:34:43.501 › I would run, but we're on battery :(
09:34:52.820 › closeRunningScreensavers
```

Looks like you were right about the battery being the source of the problem, but the solution did not fix it. 

But the good news is that disabling the "don't run on battery" option makes it work! Luckily for me, my office only uses desktop computers so it should be no problem to disable this option.

But I'd be happy to keep helping you debugging the issue.

**Comment by muffinista** [comment]
This is [hopefully fixed](https://github.com/muffinista/before-dawn/releases/tag/v0.11.4), thanks for your help debugging!

**Comment by vincerubinetti** [comment]
Success! With the "disable on battery" option checked/selected, the screensaver still runs. It looks like it is fixed.

**Comment by muffinista** [comment]
Great!
